import os
from datetime import datetime, timedelta
from typing import Dict, Optional

import stripe
from fastapi import Depends, FastAPI, HTTPException, status, Body
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from jose import JWTError, jwt
from passlib.context import CryptContext
from pydantic import BaseModel, EmailStr, Field

# ----------------------------------------------------------------------
# In‑memory "database"
# ----------------------------------------------------------------------
# The key is the user's email address; the value is a User instance.
users_db: Dict[str, "User"] = {}


# ----------------------------------------------------------------------
# Settings & security utilities
# ----------------------------------------------------------------------
SECRET_KEY = os.getenv("SECRET_KEY", "supersecretkey")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
EMAIL_TOKEN_EXPIRE_MINUTES = 60

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
# The tokenUrl must match the path of the login endpoint.
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/login")

# Stripe configuration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
if not STRIPE_SECRET_KEY:
    raise RuntimeError("STRIPE_SECRET_KEY environment variable not set")
stripe.api_key = STRIPE_SECRET_KEY


def get_password_hash(password: str) -> str:
    """Hash a plain password using bcrypt."""
    return pwd_context.hash(password)


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plain password against its bcrypt hash."""
    return pwd_context.verify(plain_password, hashed_password)


def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    """Create a JWT access token.

    The token contains the supplied ``data`` and an expiration claim.
    """
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def create_email_token(email: str) -> str:
    """Create a token used for email verification (not used in this task)."""
    expire = datetime.utcnow() + timedelta(minutes=EMAIL_TOKEN_EXPIRE_MINUTES)
    to_encode = {"sub": email, "exp": expire, "type": "email_verification"}
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def decode_token(token: str) -> dict:
    """Decode a JWT token and return its payload.

    Raises ``HTTPException`` with 401 if the token is invalid or expired.
    """
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except JWTError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials",
        ) from exc


# ----------------------------------------------------------------------
# Pydantic models
# ----------------------------------------------------------------------
class User(BaseModel):
    email: EmailStr
    hashed_password: str
    is_active: bool = True


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


class InferenceInput(BaseModel):
    """Schema for the inference request payload."""
    text: str = Field(..., description="Input text for the AI model.")


class InferenceResult(BaseModel):
    """Schema for the inference response."""
    result: str = Field(..., description="Result generated by the AI model.")


# ----------------------------------------------------------------------
# FastAPI app
# ----------------------------------------------------------------------
app = FastAPI(title="BMAI API", version="0.1.0")


# ----------------------------------------------------------------------
# Dependency: get current user from token
# ----------------------------------------------------------------------
def get_current_user(token: str = Depends(oauth2_scheme)) -> User:
    payload = decode_token(token)
    email: str = payload.get("sub")
    if email is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token payload missing subject",
        )
    user = users_db.get(email)
    if user is None or not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="User not found or inactive",
        )
    return user


# ----------------------------------------------------------------------
# Authentication endpoints
# ----------------------------------------------------------------------
@app.post("/login", response_model=TokenResponse, tags=["auth"])
async def login(form_data: OAuth2PasswordRequestForm = Depends()):
    """
    Authenticate a user and return a JWT access token.
    """
    user = users_db.get(form_data.username)
    if not user:
        raise HTTPException(status_code=400, detail="Incorrect email or password")
    if not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(status_code=400, detail="Incorrect email or password")
    access_token = create_access_token(data={"sub": user.email})
    return TokenResponse(access_token=access_token)


# ----------------------------------------------------------------------
# Helper: dummy AI model inference
# ----------------------------------------------------------------------
def dummy_model_inference(text: str) -> str:
    """
    Placeholder for the real AI model inference.
    For demonstration, it simply reverses the input text.
    """
    return text[::-1]


# ----------------------------------------------------------------------
# Inference endpoint (protected)
# ----------------------------------------------------------------------
@app.post("/infer", response_model=InferenceResult, tags=["inference"])
async def infer(
    payload: InferenceInput = Body(...),
    current_user: User = Depends(get_current_user),
):
    """
    Run AI model inference on the provided input.

    - **payload.text**: The text to be processed by the model.
    - Returns a JSON object containing the inference result.
    """
    try:
        result = dummy_model_inference(payload.text)
        return InferenceResult(result=result)
    except Exception as exc:
        # Log the exception in a real-world scenario
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred during model inference.",
        ) from exc


# ----------------------------------------------------------------------
# Example: create a default user for quick testing (remove in production)
# ----------------------------------------------------------------------
def _create_default_user():
    email = "test@example.com"
    if email not in users_db:
        users_db[email] = User(
            email=email,
            hashed_password=get_password_hash("testpassword"),
            is_active=True,
        )


_create_default_user()